// <auto-generated />
namespace WorkoutTracker.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Add_sp_GetTotalWorkoutTimesReport : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_sp_GetTotalWorkoutTimesReport));
        
        string IMigrationMetadata.Id
        {
            get { return "201804161840131_Add_sp_GetTotalWorkoutTimesReport"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
